name: ci
on:
  push:
    branches:
      - "main"
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build the docker image
        run: docker build -t python_restapi_$(date +%s) .
